<?php

namespace UsersBundle\Repository;

/**
 * SubjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectsRepository extends \Doctrine\ORM\EntityRepository
{
}
